### ISSUE TITLE
Default middleware for request validation, like IIS has

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/BasicMiddleware#64]
Remember this?

```
<configuration>
   <system.web>
      <pages validateRequest="true" />
   </system.web>
</configuration>
```

http://www.asp.net/whitepapers/request-validation

The awesome thing about IIS ASP.NET websites is that they prevented html/script injections AS A DEFAULT!

In .NET Core, it isn't even possible.

I think there should be a middleware that does validation on posted form values, http headers, etc.

Maybe some of the Microsoft employees here can ping the IIS team for the code ;)

**Comment by blowdart** [comment]
RequestValidation was always rather porous, and eventually we came to the realisation that validate should be an app concern, because what's validate for one application isn't valid for another,

We encode output by default, which is a much better approach to XSS.

It won't make a return.

**Comment by pauldotknopf** [comment]
> We encode output by default, which is a much better approach to XSS.

Do you mean in Razor, with the ```<div>@Model.Value</div>```?

> validate should be an app concern

There isn't official guidance on this. I get it, everybody could roll their own, but your not worried about the number of ```File > New > Project``` projects that will be exposed? I'm not even seeing MVC action attributes that do request validation.

**Comment by blowdart** [comment]
Yes, I mean the @ in Razor. 

Encoding is a far better way to mitigate against XSS than any sort of filtering, which is why I'm not worried File > New Project being exposed.

The request shouldn't be what's validated, it should be the inbound model.

**Comment by uandrei** [comment]
Any updates on whether this will be added to the feature list at some point or not?

**Comment by DamianEdwards** [comment]
We have no plans to ever build a request validation middleware like what existed in System.Web.

**Comment by lepipele** [comment]
"RequestValidation was always rather porous", " we came to the realization that validate should be an app concern"...

I can't even imagine how many newbs were saved by this being enabled by default. In order to shoot yourself in foot you needed to explicitly disable it. Now, anybody writing @Html.Raw needs to be knowledgeable enough to consider every possible XSS scenario.

So, while you are it you should maybe tell "BasicDataware team" to remove SQL Injection protection when using SqlValueParameter... like why not? 

It would be much more honest for you guys to say that you are just too lazy to build this... Which I also don't get... it's probably like 1 day project. I'll link here in case I build Interceptor that deals with this, if anyone else form open source community beats me to it - please post link. Thanks.

**Comment by davidfowl** [comment]
We don’t think the feature is a good one (otherwise we would have.l built it in again) and we think that there are much better ways to do it. If you want to bring back request validation, feel free to do so as a middleware.

**Comment by lepipele** [comment]
@davidfowl I get it - it's easy to say this is judgment call. But it does make sense to have something that you can easily turn on in config / initialization. That way you save bunch of people from writing BaseRequest classes that do validation + can validate HTTP calls that are not necessarily request DTOs.

Anyways, I'll link here if implement middleware that deals with this & thanks for taking time to reply.
